---
- name: ensure user exists (it should already exists)
  user:
    name: pleroma
    shell: /bin/bash
    home: /opt/pleroma
    system: true

# https://www.postgresql.org/download/linux/ubuntu/
- name: install PostgreSQL APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: install PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"

# The major version needs to be in sync with RDS
# https://github.com/dabr-ca/infra/blob/d2b06f5bada3e14c60a9a227e866575db3ce7639/modules/pleroma/postgres.tf#L9
- name: install PostgreSQL client
  apt:
    name: postgresql-client-13
    update_cache: true

- name: install Ansible and boto3
  apt:
    name:
      - ansible
      - python3-boto3

- name: make dir
  file:
    path: "{{ pg_dump_home }}"
    state: directory
    owner: pleroma
    group: pleroma
    mode: 0755

- name: copy playbook
  copy:
    src: do_pg_dump.yaml
    dest: "{{ pg_dump_home }}/do_pg_dump.yaml"
    owner: pleroma
    group: pleroma
    mode: 0644

- name: render systemd units
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - pg_dump.service
    - pg_dump.timer

- name: start systemd timer
  systemd:
    name: pg_dump.timer
    state: started
    enabled: true
    daemon_reload: true
