---
# https://www.postgresql.org/download/linux/ubuntu/
- name: install PostgreSQL APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: install PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"

# The major version needs to be in sync with RDS
# https://github.com/dabr-ca/infra/blob/d2b06f5bada3e14c60a9a227e866575db3ce7639/modules/pleroma/postgres.tf#L9
- name: install PostgreSQL client
  apt:
    name: postgresql-client-13
    update_cache: true

- name: configure database credentials
  template:
    src: pgpass
    dest: "{{ ansible_env.HOME }}/.pgpass"
    mode: 0600

- name: install Ansible
  apt:
    name:
      - ansible

- name: make dir
  file:
    paht: "{{ item }}"
    state: directory
    owner: pleroma
    group: pleroma
    mode: 0755
    with_items:
      - "{{ pg_dump_home }}"

- name: copy playbook
  copy:
    src: do_pg_dump.yaml
    dest: "{{ pg_dump_home }}/do_pg_dump.yaml"
    owner: pleroma
    group: pleroma
    mode: 0644
