---
- name: ensure user exists (it should already exists)
  user:
    name: pleroma
    shell: /bin/bash
    home: /opt/pleroma
    system: true

- name: install Ansible and boto3
  apt:
    name:
      - ansible
      - python3-boto3

- name: make dir
  file:
    path: "{{ pg_dump_home }}"
    state: directory
    owner: pleroma
    group: pleroma
    mode: 0755

- name: copy playbook
  copy:
    src: do_pg_dump.yaml
    dest: "{{ pg_dump_home }}/do_pg_dump.yaml"
    owner: pleroma
    group: pleroma
    mode: 0644

- name: render systemd units
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - pg_dump.service
    - pg_dump.timer

- name: start systemd timer
  systemd:
    name: pg_dump.timer
    state: started
    enabled: true
    daemon_reload: true
