pleroma_ver: "v2.10.2"
pleroma_tarball_url: "https://github.com/dabr-ca/pleroma-otp/releases/download/{{ pleroma_ver }}/pleroma-otp-{{ pleroma_ver }}-arm64.tar.gz"
pleroma_tarball_checksum: "sha256:6daaa47acce5620d802d667bc48ad6bf24ec0c72cba41934019df4b510e4cdd4"

pleroma_home: /opt/pleroma
pleroma_data: /var/lib/pleroma
pleroma_config: /etc/pleroma
pleroma_secret_exs_ssm_parameter: /dabr-ca/pleroma/secret_exs

rds_bundle_path: /etc/ssl/certs/rds-bundle.pem
